//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string Fullname { get; set; }
        public string Pass { get; set; }
        public string Usertype { get; set; }
    }
}
